ALTER TABLE DEVELOPER
add salary int;

UPDATE DEVELOPER set DEVELOPER.salary = 2000 where ID = 1;

UPDATE DEVELOPER set DEVELOPER.salary = 6000 where ID = 2;

UPDATE DEVELOPER set DEVELOPER.salary = 8000 where ID = 3;