SELECT sum(SALARY)
from DEVELOPER
         join DEVELOPER_SKILL on DEVELOPER.ID = DEVELOPER_skill.DEVELOPER_ID
         join SKILL on DEVELOPER_SKILL.SKILL_ID = SKILL.ID
where SKILL.TECHNOLOGY = 'Java';
