SELECT avg(SALARY)
from DEVELOPER
         join DEVELOPER_PROJECT on DEVELOPER.ID = DEVELOPER_PROJECT.DEVELOPER_ID
         join PROJECT  on DEVELOPER_PROJECT.PROJECT_ID = PROJECT.ID
where COST in (SELECT min(COST) from PROJECT)



